version: '3.9'
services:
  api:
    build: .
    container_name: robotcaller_api
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - postgres
      - redis
      - asterisk
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: robotcaller_frontend
    ports:
      - "7331:7331"
    environment:
      - API_URL=http://localhost:8000

  postgres:
    image: postgres:16
    container_name: robotcaller_db
    environment:
      POSTGRES_USER: caller
      POSTGRES_PASSWORD: caller
      POSTGRES_DB: robotcaller
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: robotcaller_redis

  worker:
    build: .
    container_name: robotcaller_worker
    command: celery -A worker.celery_app worker --loglevel=info
    depends_on:
      - redis
      - api

  asterisk:
    image: andrius/asterisk
    container_name: robotcaller_asterisk
    ports:
      - "5060:5060/udp"
      - "8088:8088"
    volumes:
      - ./pjsip.conf:/etc/asterisk/pjsip.conf
      - ./sounds:/var/lib/asterisk/sounds

volumes:
  db_data:
